Cancel = "Cancel"
CommandRunMenu = "Are you sure you want to run this scripts?"
Copy = "Copy"
Explanation = "Explanation:"
Menu = "What would you do with this script?"
Revise = "Revise"
ReviseMenu = "What would you like spark to change this scripts?"
ReviseResult = "Your new scripts:"
Run = "Run"
RunResult = "Run Results:"
YourScripts = "Your Scripts:"
