Cancel = "取消"
CommandRunMenu = "确认执行此脚本吗?"
Copy = "拷贝"
Explanation = "解释如下:"
Menu = "修改此脚本吗?"
Revise = "修改"
ReviseMenu = "What would you like spark to change this scripts?"
ReviseResult = "修改结果如下:"
Run = "运行"
RunResult = "执行结果:"
YourScripts = "您的脚本如下:"